"""The manka-shreds Python SDK: a subscriber client for the manka-shreds shred stream.

See ``README.md`` for a walkthrough. The short version::

    import asyncio, os
    from manka_shreds_sdk import Client, Stream

    async def main():
        client = await Client.connect(
            host="node.example.com",
            port=9000,
            secret=os.environ["MANKA_SHREDS_SECRET"],
            streams=Stream.TRANSACTIONS,
        )
        async for event in client:
            if event.type == "transaction":
                tx = event.transaction
                print(tx.slot, tx.signature.hex() if tx.signature else None)

    asyncio.run(main())

Two things reach a node: its address and your secret. The address is an argument, so one build
serves every node. The secret never crosses the wire — see :mod:`manka_shreds_sdk.handshake`.
"""

from __future__ import annotations

from . import handshake
from .client import (
    Client,
    DuplicateEvent,
    EntryEvent,
    Event,
    FilterAckEvent,
    LagEvent,
    PingEvent,
    PongEvent,
    RawShredEvent,
    SlotEndEvent,
    SlotStartEvent,
    TransactionEvent,
    UnknownEvent,
)
from .dictcache import CACHE_ENV, DictionaryCache, default_dir
from .events import (
    DUPLICATE_LEN,
    ENTRY_LEN,
    RAW_SHRED_HEADER_LEN,
    SLOT_END_LEN,
    SLOT_START_LEN,
    Duplicate,
    Entry,
    RawShred,
    SlotEnd,
    SlotStart,
    read_duplicate,
    read_entry,
    read_raw_shred,
    read_slot_end,
    read_slot_start,
)
from .protocol import (
    ALL_STREAMS,
    DICTIONARY_HEADER_LEN,
    FRAME_HEADER_LEN,
    HELLO_ACK_LEN,
    MAX_DICTIONARY_BYTES,
    MAX_FRAME_PAYLOAD,
    MAX_HANDSHAKE_BYTES,
    PROTOCOL_VERSION,
    Capability,
    Challenge,
    Codec,
    CodecBit,
    Dictionary,
    ErrorCode,
    FilterAck,
    FrameHeader,
    FrameKind,
    Hello,
    HelloAck,
    Lag,
    NamedFilter,
    ProtocolError,
    ServerError,
    Stream,
    Verification,
    dictionary_id,
    read_challenge,
    read_dictionary,
    read_error,
    read_filter_ack,
    read_frame_header,
    read_hello_ack,
    read_lag,
    write_dictionary,
    write_frame,
    write_hello,
    write_prove,
    write_set_filter,
)
from .transaction import (
    INSTRUCTION_ENTRY_LEN,
    LOOKUP_ENTRY_LEN,
    MESSAGE_VERSION_LEGACY,
    TX_HEADER_LEN,
    AddressLookup,
    Instruction,
    Transaction,
    TxFlag,
)
from .transport import (
    ALPN,
    Fingerprint,
    ServerVerification,
    Transport,
    TransportError,
    Unchecked,
    Wire,
    connect_quic,
    connect_tcp,
    fingerprint_of,
)

__version__ = "0.1.0"

__all__ = [
    "ALL_STREAMS",
    "ALPN",
    "CACHE_ENV",
    "DICTIONARY_HEADER_LEN",
    "DUPLICATE_LEN",
    "ENTRY_LEN",
    "FRAME_HEADER_LEN",
    "HELLO_ACK_LEN",
    "INSTRUCTION_ENTRY_LEN",
    "LOOKUP_ENTRY_LEN",
    "MAX_DICTIONARY_BYTES",
    "MAX_FRAME_PAYLOAD",
    "MAX_HANDSHAKE_BYTES",
    "MESSAGE_VERSION_LEGACY",
    "PROTOCOL_VERSION",
    "RAW_SHRED_HEADER_LEN",
    "SLOT_END_LEN",
    "SLOT_START_LEN",
    "TX_HEADER_LEN",
    "AddressLookup",
    "Capability",
    "Challenge",
    "Client",
    "Codec",
    "CodecBit",
    "Dictionary",
    "DictionaryCache",
    "Duplicate",
    "DuplicateEvent",
    "Entry",
    "EntryEvent",
    "ErrorCode",
    "Event",
    "FilterAck",
    "FilterAckEvent",
    "Fingerprint",
    "FrameHeader",
    "FrameKind",
    "Hello",
    "HelloAck",
    "Instruction",
    "Lag",
    "LagEvent",
    "NamedFilter",
    "PingEvent",
    "PongEvent",
    "ProtocolError",
    "RawShred",
    "RawShredEvent",
    "ServerError",
    "ServerVerification",
    "SlotEnd",
    "SlotEndEvent",
    "SlotStart",
    "SlotStartEvent",
    "Stream",
    "Transaction",
    "TransactionEvent",
    "Transport",
    "TransportError",
    "TxFlag",
    "Unchecked",
    "UnknownEvent",
    "Verification",
    "Wire",
    "__version__",
    "connect_quic",
    "connect_tcp",
    "default_dir",
    "dictionary_id",
    "fingerprint_of",
    "handshake",
    "read_challenge",
    "read_dictionary",
    "read_duplicate",
    "read_entry",
    "read_error",
    "read_filter_ack",
    "read_frame_header",
    "read_hello_ack",
    "read_lag",
    "read_raw_shred",
    "read_slot_end",
    "read_slot_start",
    "write_dictionary",
    "write_frame",
    "write_hello",
    "write_prove",
    "write_set_filter",
]
